# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5484ad29580dd5077c03e71bb3938d5a5257922b59b3f857d85d234325525eb7d17944ffff0f1139ff55eb2f171b8f4305e8dd94bc871c2b098e127df70b3528

test:
  secret_key_base: 010bcc9cb4041320a910b37c5acdde59f3443fb815639940ad3008190962e3f844a6ed52477c8df659ae1af93f85a942197923ddb6ab5608d943164fedd703eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
